package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DestinoLixo generated by hbm2java
 */
@Entity
@Table(name="destino_lixo"
    ,catalog="ficha"
)
public class DestinoLixo  implements java.io.Serializable {


     private Integer id;
     private String destinoLixo;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public DestinoLixo() {
    }

    public DestinoLixo(String destinoLixo, Set<Domicilio> domicilios) {
       this.destinoLixo = destinoLixo;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="DESTINO_LIXO", length=45)
    public String getDestinoLixo() {
        return this.destinoLixo;
    }
    
    public void setDestinoLixo(String destinoLixo) {
        this.destinoLixo = destinoLixo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="destinoLixo")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


