package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="ficha"
)
public class Endereco  implements java.io.Serializable {


     private Integer id;
     private String tipoLogradoro;
     private String nomeLogradoro;
     private String complemento;
     private String bairro;
     private String municipio;
     private String uf;
     private String cep;
     private Integer numero;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public Endereco() {
    }

    public Endereco(String tipoLogradoro, String nomeLogradoro, String complemento, String bairro, String municipio, String uf, String cep, Integer numero, Set<Domicilio> domicilios) {
       this.tipoLogradoro = tipoLogradoro;
       this.nomeLogradoro = nomeLogradoro;
       this.complemento = complemento;
       this.bairro = bairro;
       this.municipio = municipio;
       this.uf = uf;
       this.cep = cep;
       this.numero = numero;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="TIPO_LOGRADORO", length=20)
    public String getTipoLogradoro() {
        return this.tipoLogradoro;
    }
    
    public void setTipoLogradoro(String tipoLogradoro) {
        this.tipoLogradoro = tipoLogradoro;
    }

    
    @Column(name="NOME_LOGRADORO", length=45)
    public String getNomeLogradoro() {
        return this.nomeLogradoro;
    }
    
    public void setNomeLogradoro(String nomeLogradoro) {
        this.nomeLogradoro = nomeLogradoro;
    }

    
    @Column(name="COMPLEMENTO", length=185)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="BAIRRO", length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="MUNICIPIO", length=45)
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    
    @Column(name="UF", length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="CEP", length=45)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="NUMERO")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="endereco")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


