package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProducaoRural generated by hbm2java
 */
@Entity
@Table(name="producao_rural"
    ,catalog="ficha"
)
public class ProducaoRural  implements java.io.Serializable {


     private Integer id;
     private String producaoRural;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public ProducaoRural() {
    }

    public ProducaoRural(String producaoRural, Set<Domicilio> domicilios) {
       this.producaoRural = producaoRural;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="PRODUCAO_RURAL", length=85)
    public String getProducaoRural() {
        return this.producaoRural;
    }
    
    public void setProducaoRural(String producaoRural) {
        this.producaoRural = producaoRural;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producaoRural")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


