package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profissional generated by hbm2java
 */
@Entity
@Table(name="profissional"
    ,catalog="ficha"
)
public class Profissional  implements java.io.Serializable {


     private Integer id;
     private Integer cartId;
     private String cnes;
     private String equipe;
     private String microarea;
     private Date data;
     private String nome;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public Profissional() {
    }

    public Profissional(Integer cartId, String cnes, String equipe, String microarea, Date data, String nome, Set<Domicilio> domicilios) {
       this.cartId = cartId;
       this.cnes = cnes;
       this.equipe = equipe;
       this.microarea = microarea;
       this.data = data;
       this.nome = nome;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CART_ID")
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    
    @Column(name="CNES", length=7)
    public String getCnes() {
        return this.cnes;
    }
    
    public void setCnes(String cnes) {
        this.cnes = cnes;
    }

    
    @Column(name="EQUIPE", length=10)
    public String getEquipe() {
        return this.equipe;
    }
    
    public void setEquipe(String equipe) {
        this.equipe = equipe;
    }

    
    @Column(name="MICROAREA", length=2)
    public String getMicroarea() {
        return this.microarea;
    }
    
    public void setMicroarea(String microarea) {
        this.microarea = microarea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATA", length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="NOME", length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profissional")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


