package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TelefoneReferencia generated by hbm2java
 */
@Entity
@Table(name="telefone_referencia"
    ,catalog="ficha"
)
public class TelefoneReferencia  implements java.io.Serializable {


     private Integer id;
     private String telefone;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public TelefoneReferencia() {
    }

    public TelefoneReferencia(String telefone, Set<Domicilio> domicilios) {
       this.telefone = telefone;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="TELEFONE", length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="telefoneReferencia")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


