package com.celso.fichaa.model;
// Generated 25/05/2015 08:57:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TratamentoAgua generated by hbm2java
 */
@Entity
@Table(name="tratamento_agua"
    ,catalog="ficha"
)
public class TratamentoAgua  implements java.io.Serializable {


     private Integer id;
     private String tratamentoAgua;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public TratamentoAgua() {
    }

    public TratamentoAgua(String tratamentoAgua, Set<Domicilio> domicilios) {
       this.tratamentoAgua = tratamentoAgua;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="TRATAMENTO_AGUA", length=45)
    public String getTratamentoAgua() {
        return this.tratamentoAgua;
    }
    
    public void setTratamentoAgua(String tratamentoAgua) {
        this.tratamentoAgua = tratamentoAgua;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tratamentoAgua")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


